### ISSUE TITLE
Parse the Data

### ISSUE THREAD

**Issue by vlisna789** [juniordesign-fall18/skim#3]
The UAH course data is formatted as a text file. We need to grab the specific data necessary for our database.

**Comment by nikitarajput** [comment]
We need the following information for each course:
- [ ] Course Number
- [ ] Section Number
- [ ] Title
- [ ] Max Enrollment
- [ ] Current Enrollment
- [ ] Available Seats
- [ ] Semester 
- [ ]  Year
